version: '3'
services:
  comment:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    container_name: comment
    stdin_open: true
    volumes:
       - .:/app
    env_file:
      - .env